In [ ]:
pip install numpy

In [2]:
import numpy as np 



In [4]:
a=np.array([1, 2, 3]) 
a

array([1, 2, 3])

In [8]:
a.dtype

dtype('int32')

In [9]:
type(a) 

numpy.ndarray

In [5]:
w=[1, 2, 3]
print(type(w))

<class 'list'>


In [10]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
b[0]


array([1.5, 2. , 3. ])

In [13]:
b[0,0]

1.5

In [12]:
b[0][0]

1.5

In [15]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex128) 
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [16]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones((3, 2, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.empty((3, 3)) 


array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.44261602e-321],
       [4.10463701e-288, 2.29812144e-311, 0.00000000e+000]])

Функция empty() создает массив без его заполнения. Исходное содержимое 
случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится): 


In [22]:
a=np.empty((3, 3))
a

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [23]:
a[0, 0]=89


In [21]:
a

array([[8.90000000e+001, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.48214127e-321],
       [4.10463701e-288, 2.29812144e-311, 1.60205318e-306]])

In [19]:
np.arange(10, 30, 5)


array([10, 15, 20, 25])

In [20]:
np.arange(0, 1, 0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
def f1(i, j): 
    return 3 * i + j 
np.fromfunction(f1, (3, 4)) 


array([[0., 1., 2., 3.],
       [3., 4., 5., 6.],
       [6., 7., 8., 9.]])

In [26]:
np.fromfunction(f1, (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
print(np.arange(0, 3000, 1))


[   0    1    2 ... 2997 2998 2999]


In [33]:
np.set_printoptions(threshold=inf) 

In [29]:
np.set_printoptions(precision=4)

In [30]:
np.array([1.123456789])

array([1.1235])

In [34]:
print(np.arange(0, 3000, 1))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

In [35]:
 a = np.array([20, 30, 40, 50]) 

In [36]:
b = np.arange(4) 
b

array([0, 1, 2, 3])

In [37]:
a+b

array([20, 31, 42, 53])

In [38]:
 a - b 

array([20, 29, 38, 47])

In [39]:
a * b

array([  0,  30,  80, 150])

In [40]:
a / b

<ipython-input-40-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([    inf, 30.    , 20.    , 16.6667])

In [41]:
a ** b

array([     1,     30,   1600, 125000], dtype=int32)

In [43]:
a % b

<ipython-input-43-bb5d1a9b79f9>:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([0, 0, 0, 2], dtype=int32)

In [44]:
c = np.array([[1, 2, 3], [4, 5, 6]]) 
d = np.array([[1, 2], [3, 4], [5, 6]]) 


In [45]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
c + d 


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [48]:
a + 1


array([21, 31, 41, 51])

In [50]:
a**3

array([  8000,  27000,  64000, 125000], dtype=int32)

In [51]:
a

array([20, 30, 40, 50])

In [52]:
a< 35

array([ True,  True, False, False])

In [53]:
np.cos(a)


array([ 0.4081,  0.1543, -0.6669,  0.965 ])

In [61]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.sum(a)

21

In [59]:
a=a.sum()

In [57]:
a.min()


1

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a.min(axis=0)

array([1, 2, 3])

In [66]:
a.min(axis=1) 

array([1, 4])

In [67]:
a = np.arange(10) ** 3 
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [68]:
a[5]

125

In [69]:
a[5]=900
a

array([  0,   1,   8,  27,  64, 900, 216, 343, 512, 729], dtype=int32)

In [70]:
a[3:7]

array([ 27,  64, 900, 216], dtype=int32)

In [71]:
 a[::-1] 


array([729, 512, 343, 216, 900,  64,  27,   8,   1,   0], dtype=int32)

In [73]:
for i in a: 
    print(i** (1/3))

0.0
1.0
2.0
3.0
3.9999999999999996
9.654893846056297
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [74]:
b = np.array([[ 0, 1, 2, 3], 
    [10, 11, 12, 13], 
    [20, 21, 22, 23], 
    [30, 31, 32, 33], 
    [40, 41, 42, 43]]) 


In [75]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [76]:
 b[2,3] 
    

23

In [77]:
 b[(2,3)]

23

In [78]:
 b[2][3]

23

In [79]:
 b[:,2] 

array([ 2, 12, 22, 32, 42])

In [80]:
 b[:2] 

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [81]:
 b[1:3, : : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [82]:
 b[-1] 

array([40, 41, 42, 43])

In [83]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]])) 

In [84]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [85]:
a.shape 


(2, 2, 3)

In [86]:
a[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [87]:
a[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [88]:
a[1, : , :] 

array([[100, 101, 102],
       [110, 112, 113]])

In [89]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
c[... ,2] 

array([3, 6])

In [91]:
for row in a:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [92]:
 a.shape 


(2, 2, 3)

In [93]:
c.shape 


(2, 3)

In [94]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [95]:
a.ravel() 

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [97]:
a.shape = (6, 2) 

In [98]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [99]:
a.transpose()

array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

In [100]:
a.reshape((3, 4)) 

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [101]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [102]:
a.reshape((3, 4), order='F') 

array([[  0, 100,   1, 101],
       [  2, 102,  10, 110],
       [ 12, 112,  13, 113]])

In [103]:
a

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [104]:
a.resize((2, 6))

In [105]:
a

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [106]:
a.reshape((3, -1)) 

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [108]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [109]:
b = np.array([[5, 6], [7, 8]]) 
b

array([[5, 6],
       [7, 8]])

In [110]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [111]:
np.hstack((a, b)) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [112]:
 np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [113]:
 np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [114]:
a = np.arange(12).reshape((2, 6)) 
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [115]:
 np.hsplit(a, 3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [116]:
np.hsplit(a, (3, 4)) 

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [120]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
b = a

In [122]:
 b is a

True

In [123]:
b[0]=100

In [124]:
a,b

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]),
 array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]))

In [125]:
b.shape = (3,4) 

In [126]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [127]:
a.shape

(3, 4)

In [128]:
 c = a.view() 

In [129]:
c is a 


False

In [130]:
c.base is a 

True

In [131]:
a,c

(array([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]),
 array([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]))

In [132]:
c[0]=555

In [133]:
c

array([[555, 555, 555, 555],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [134]:
a

array([[555, 555, 555, 555],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [135]:
c.shape = (2,6) 

In [136]:
c

array([[555, 555, 555, 555,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [137]:
a.shape

(3, 4)

In [138]:
d = a.copy() 

In [139]:
d

array([[555, 555, 555, 555],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [140]:
d is a 

False

In [141]:
d.base is a

False

In [143]:
d[0, 0] = 9999
d

array([[9999,  555,  555,  555],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [144]:
a

array([[555, 555, 555, 555],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [145]:
np.poly([-1, 1, 1, 10]) 

array([  1., -11.,   9.,  11., -10.])

In [146]:
np.roots([1, 4, -2, 3])


array([-4.5797+0.j    ,  0.2899+0.7557j,  0.2899-0.7557j])

In [147]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float) 
a

array([1., 4., 3., 8., 9., 2., 3.])

In [148]:
np.median(a) 


3.0

In [149]:
 a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float) 

In [150]:
c = np.corrcoef(a) 


In [151]:
c

array([[1.    , 0.7287],
       [0.7287, 1.    ]])

In [152]:
np.cov(a)


array([[0.9167, 2.0833],
       [2.0833, 8.9167]])

In [153]:
np.random.random(10) 


array([0.9213, 0.8975, 0.7879, 0.0369, 0.7558, 0.8008, 0.2155, 0.7678,
       0.2961, 0.5728])

In [156]:
 np.random.seed(15) 

In [157]:
np.random.random(10) 


array([0.8488, 0.1789, 0.0544, 0.3615, 0.2754, 0.53  , 0.3059, 0.3045,
       0.1117, 0.2499])

In [159]:
np.random.seed(15) 
np.random.random(10) 

array([0.8488, 0.1789, 0.0544, 0.3615, 0.2754, 0.53  , 0.3059, 0.3045,
       0.1117, 0.2499])

In [160]:
state = np.random.get_state() 
state

('MT19937',
 array([3633790460, 1023870981,  579752885,  281244083, 3285746077,
        1393277933, 2793080415,  399528565, 2570439006, 3334903767,
         256738830, 1067643312,  310295404, 3367851351, 1213810373,
        2939329709,  467434422, 3616569739,  366596964, 2567211770,
         371942620, 1092453803, 3601183765,  218740350, 2987419994,
        1258682074,  438232744,  791355342, 3123683486,  358690449,
        4111882543, 3646060760, 2341292923, 1360587327, 1846751523,
        1275235888, 1226614688,  995905150,  415957167, 1402826379,
        2758946168, 2068006849,  778532886, 2860840768,  830247948,
        3999540946, 2758483782, 1793068693, 1138273484, 4006794736,
        3930027703,  492481514, 3283517767, 3202239719, 1490356493,
        3413594509, 1446013626, 1925602916, 2574021657, 3433506684,
        1470601302, 4269977722, 3377783644, 1090110383, 2003452212,
         429257525, 2243188520, 2897018980,  124975205, 3096270776,
        2116564105, 3059367036,   84

In [161]:
np.random.rand(5) 

array([0.9176, 0.2641, 0.7178, 0.8657, 0.8071])

In [162]:
np.random.rand(2,3)

array([[0.2106, 0.1672, 0.0467],
       [0.0394, 0.2002, 0.9985]])

In [163]:
np.random.rand(6).reshape((2,3))

array([[0.3728, 0.7605, 0.4735],
       [0.5097, 0.945 , 0.1094]])

In [164]:
 np.random.random() 


0.46509316076483553

In [165]:
import random 


In [166]:
np.array([random.random() for i in range(10)]) 


array([0.1904, 0.2263, 0.1702, 0.3147, 0.7877, 0.5341, 0.4547, 0.8512,
       0.4715, 0.9672])

In [167]:
np.random

<module 'numpy.random' from 'C:\\Users\\home\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [168]:
import numpy.random as rand

In [169]:
rand


<module 'numpy.random' from 'C:\\Users\\home\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [170]:
np.random.sample()


0.14155525990080142

In [171]:
np.random.sample(3)


array([0.5383, 0.299 , 0.5377])

In [172]:
np.random.sample((2, 3)) 


array([[0.6656, 0.3643, 0.623 ],
       [0.6427, 0.42  , 0.4032]])

In [176]:
np.random.randint(0, 7+1, 10)


array([4, 3, 7, 4, 5, 6, 0, 1, 0, 4])

In [175]:
np.random.random_integers(0, 3, 10) 


<ipython-input-175-efd94b46b71c>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  np.random.random_integers(0, 3, 10)


array([2, 2, 0, 1, 2, 0, 3, 2, 0, 0])

In [177]:
np.random.randint(0, 3, (2, 10)) 


array([[0, 2, 2, 2, 2, 0, 2, 0, 2, 2],
       [1, 0, 1, 0, 0, 0, 2, 1, 2, 2]])

In [178]:
np.random.uniform(2, 8, (2, 10)) 


array([[6.6498, 7.785 , 7.9714, 4.1122, 5.629 , 6.1829, 3.3988, 2.8897,
        2.3176, 7.6376],
       [2.8744, 5.7052, 4.2349, 5.9306, 3.711 , 4.8301, 2.2901, 5.898 ,
        6.1275, 7.7532]])

In [179]:
 np.random.poisson(6.0) 

4

In [180]:
np.random.normal(1.5, 4.0)

1.623167578957047

In [181]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.random.shuffle(a) 


In [183]:
a

array([0, 2, 9, 6, 5, 1, 7, 3, 8, 4])

In [184]:
np.random.permutation(10)


array([2, 7, 9, 3, 8, 0, 6, 4, 1, 5])

In [185]:
a

array([0, 2, 9, 6, 5, 1, 7, 3, 8, 4])

In [186]:
a = np.arange(10) 

In [187]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
np.random.choice(a, 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 1, 0, 2, 2, 1])

In [192]:
a = np.array([1, 3, 0], float)
a

array([1., 3., 0.])

In [193]:
b = np.array([0, 3, 2], float) 
b

array([0., 3., 2.])

In [191]:
a>b

array([ True, False, False])

In [194]:
a == b 


array([False,  True, False])

In [196]:
c = a <= b
c

array([False,  True,  True])

In [197]:
a> 2 

array([False,  True, False])

In [198]:
c = np.array([ True, False, False], bool) 
any(c) 

True

In [199]:
all(c)

False

In [200]:
 a = np.array([1, 3, 0], float)

In [201]:
np.logical_and(a > 0, a < 3) 

array([ True, False, False])

In [202]:
 b = np.array([True, False, True], bool) 

In [203]:
np.logical_not(b) 

array([False,  True, False])

In [204]:
c = np.array([False, True, False], bool)

In [205]:
 np.logical_or(b, c) 


array([ True,  True,  True])

In [206]:
a = np.array([1, 3, 0], float) 

In [207]:
np.where(a != 0, 1 / a, a) 


<ipython-input-207-dd19644670bc>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a != 0, 1 / a, a)


array([1.    , 0.3333, 0.    ])

In [208]:
np.where(a> 0, 3, 2) 


array([3, 3, 2])

In [211]:
a = np.array([[0, 1], [3, 0]], float) 
a

array([[0., 1.],
       [3., 0.]])

In [210]:
a.nonzero() 

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [212]:
a = np.array([1, np.NaN, np.Inf], float) 
a 

array([ 1., nan, inf])

In [213]:
np.isnan(a) 

array([False,  True, False])

In [214]:
np.isfinite(a) 


array([ True, False, False])

In [215]:
a = np.array([1, np.NaN, np.Inf], float) 

In [216]:
a

array([ 1., nan, inf])

In [217]:
np.isnan(a) 

array([False,  True, False])

In [218]:
a = np.array([[6, 4], [5, 9]], float)
a

array([[6., 4.],
       [5., 9.]])

In [219]:
sel = (a>= 6)


In [220]:
a[sel]

array([6., 9.])

In [221]:
a[a>=6]

array([6., 9.])

In [222]:
a[np.logical_and(a > 5, a < 9)] 


array([6.])

In [224]:
a = np.array([2, 4, 6, 8], float)
a

array([2., 4., 6., 8.])

In [225]:
b = np.array([0, 0, 1, 3, 2, 1], int)
b

array([0, 0, 1, 3, 2, 1])

In [226]:
 a[b] 

array([2., 2., 4., 8., 6., 4.])

In [227]:
a[[0, 0, 1, 3, 2, 1]]


array([2., 2., 4., 8., 6., 4.])

In [231]:
a = np.array([[1, 4], [9, 16]], float) 
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [229]:
 b = np.array([0, 0, 1, 1, 0], int) 

In [230]:
 c = np.array([0, 1, 1, 1, 1], int) 


In [232]:
a[b,c]


array([ 1.,  4., 16., 16.,  4.])

In [233]:
 a = np.array([2, 4, 6, 8], float) 
a

array([2., 4., 6., 8.])

In [234]:
b = np.array([0, 0, 1, 3, 2, 1], int) 


In [235]:
a.take(b) 

array([2., 2., 4., 8., 6., 4.])

In [236]:
a = np.array([[0, 1], [2, 3]], float)
a

array([[0., 1.],
       [2., 3.]])

In [237]:
b = np.array([0, 0, 1], int) 


In [238]:
a.take(b, axis=0) 


array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [239]:
a.take(b, axis=1)


array([[0., 0., 1.],
       [2., 2., 3.]])

In [240]:
a = np.array([0, 1, 2, 3, 4, 5], float) 
a

array([0., 1., 2., 3., 4., 5.])

In [241]:
b = np.array([9, 8, 7], float) 
b

array([9., 8., 7.])

In [243]:
a.put([0, 3], b) 
a

array([9., 1., 2., 8., 4., 5.])

In [244]:
a = np.array([0, 1, 2, 3, 4, 5], float) 
a.put([0, 3], 5) 
a

array([5., 1., 2., 5., 4., 5.])

In [245]:
 tuple = ( 'abcd', 786 , 2.23, 'john', 70.2 )